### ISSUE TITLE
Markdown is not rendered

### ISSUE THREAD

**Issue by andrew-wilkes** [IranosMorloy/json-table-editor#1]
If you rename the README.txt file to README.md the markdown should render in GitHub.

**Comment by IranosMorloy** [comment]
Hello Andrew. The readme file was written to be displayed mainly inside the project when running directly from Godot Engine. But I see your point. I'll try to see if my dataparser can read MD files as well and if so, I'll change the TXT to MD.

**Comment by IranosMorloy** [comment]
Hello Andrew, so it seems I initially directly added the README text to the project itself, not needing to load the README file at all. I have thus changed the extension from TXT to MD. Thank you for reporting this. Resolved.
